### ISSUE TITLE
Please don't forget history

### ISSUE THREAD

**Issue by lintool** [styfeng/DataAug4NLP#1]
The earliest paper cited on this page appears to be from 2015, which gives the reader the impression that data augmentation is a recent invention. It is not.

Data augmentation dates from at least the 1990s. See, for example:
https://www.aclweb.org/anthology/P95-1026/

We've tried to produce a short summary in our forthcoming book about transformers for text ranking:
https://arxiv.org/pdf/2010.06467.pdf#page=7

Data augmentation is likely even older... my memory only dates back to the 1990s, from when I was a graduate student. More senior members in the community (e.g., Ed) can probably help you trace references back even further.

Please, let's not forget history.

**Comment by styfeng** [comment]
Thanks Prof. Lin for the comment! Definitely agree about the importance of history and older works. We will be adding earlier data augmentation papers to the repo, and will check out the summary in your forthcoming book.
